
services:
  backend:
    container_name: backend-rag-extraction
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./code:/code
      - ./backend/data:/app/data
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=test1234
      - QDRANT_URI=http://qdrant:6333
    depends_on:
      - neo4j
      - qdrant
    ports:
      - "8000:8000"

  neo4j:
    container_name: neo4j
    image: neo4j:5
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/test1234
      - NEO4J_dbms_memory_heap_initial__size=512M
      - NEO4J_dbms_memory_heap_max__size=1G
    volumes:
      - neo4j_data:/data
    ports:
      - "7474:7474"
      - "7687:7687"

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
    restart: always
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"

volumes:
  neo4j_data:
  qdrant_data:
